'use client'
import { useState, useEffect } from 'react'
import { supabase } from '@/utils/supabase/client'
import { useRouter } from 'next/navigation'
import { Loader2, ArrowRight, ArrowLeft, Briefcase, DollarSign, Coffee, Home, User, Heart } from 'lucide-react'

export default function Onboarding() {
  const router = useRouter()
  const [loading, setLoading] = useState(false)
  const [user, setUser] = useState<any>(null)
  const [step, setStep] = useState(1)
  const totalSteps = 6

  // --- STATE MANAGEMENT ---
  // Step 1: Basics
  const [fullName, setFullName] = useState('')
  const [city, setCity] = useState('')
  const [gender, setGender] = useState('')
  const [intent, setIntent] = useState('dating_marriage')

  // Step 2: Career
  const [jobTitle, setJobTitle] = useState('')
  const [company, setCompany] = useState('')
  const [industry, setIndustry] = useState('')
  const [careerGhostMode, setCareerGhostMode] = useState(true) // Default private

  // Step 3: Financials
  const [income, setIncome] = useState(12) // Default 12L

  // Step 4: Lifestyle
  const [diet, setDiet] = useState('')
  const [drink, setDrink] = useState('')
  const [smoke, setSmoke] = useState('')

  // Step 5: Roots
  const [religion, setReligion] = useState('')
  const [familyType, setFamilyType] = useState('')

  // Step 6: Preferences
  const [prefMinAge, setPrefMinAge] = useState('24')
  const [prefMaxAge, setPrefMaxAge] = useState('30')

  useEffect(() => {
    const getUser = async () => {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) router.push('/login')
      setUser(user)
    }
    getUser()
  }, [])

  // --- VALIDATION & NAVIGATION ---
  const handleNext = () => {
      // Basic validation per step
      if (step === 1 && (!fullName || !city || !gender)) return alert("Please fill all details.")
      if (step === 2 && (!jobTitle || !company)) return alert("Career details help find better matches.")
      
      setStep(prev => prev + 1)
  }

  const handleBack = () => setStep(prev => prev - 1)

  // --- FINAL SUBMISSION ---
  const handleComplete = async () => {
    setLoading(true)

    // 1. Update Profile (Basics + JSON Data)
    const { error: profileError } = await supabase
        .from('profiles')
        .upsert({
            id: user.id,
            full_name: fullName,
            city: city,
            intent: intent,
            gender: gender,
            income_level: `${income}L`,
            lifestyle: { diet, drink, smoke },
            roots: { religion, familyType },
            partner_preferences: { min_age: prefMinAge, max_age: prefMaxAge },
            slots_limit: 3,
            is_gold: false,
            // brand_id is auto-generated by DB
        })

    // 2. Update Career Data (Separate Table)
    const { error: careerError } = await supabase
        .from('career_data')
        .upsert({
            user_id: user.id,
            role: jobTitle,
            industry: industry,
            company_real_name: company,
            company_display_name: careerGhostMode ? "Top Tier Firm" : company, // Privacy Logic
        })

    if (profileError || careerError) {
        alert("Error saving profile. Please try again.")
        console.error(profileError, careerError)
    } else {
        router.push('/')
    }
    setLoading(false)
  }

  // Helper to render progress
  const ProgressBar = () => (
      <div className="flex gap-1 mb-6">
          {[...Array(totalSteps)].map((_, i) => (
              <div key={i} className={`h-1.5 flex-1 rounded-full ${i + 1 <= step ? 'bg-slate-900' : 'bg-slate-200'}`} />
          ))}
      </div>
  )

  return (
    <div className="min-h-screen bg-white p-6 flex flex-col max-w-md mx-auto">
      
      {/* HEADER */}
      <div className="mb-6 pt-4">
        {step > 1 && (
            <button onClick={handleBack} className="mb-4 p-2 -ml-2 rounded-full hover:bg-slate-50 w-fit">
                <ArrowLeft size={24} className="text-slate-600" />
            </button>
        )}
        <ProgressBar />
        <h1 className="text-2xl font-serif font-bold text-slate-900">
            {step === 1 && "The Basics"}
            {step === 2 && "Career Details"}
            {step === 3 && "Financials"}
            {step === 4 && "Lifestyle"}
            {step === 5 && "Roots & Values"}
            {step === 6 && "Partner Preferences"}
        </h1>
        <p className="text-slate-500 text-sm mt-1">
            {step === 1 && "Let's start with your identity."}
            {step === 2 && "What do you do for a living?"}
            {step === 3 && "This helps find lifestyle matches."}
            {step === 4 && "Your daily habits matter."}
            {step === 5 && "A bit about your background."}
            {step === 6 && "Who are you looking for?"}
        </p>
      </div>

      {/* --- STEP 1: BASICS --- */}
      {step === 1 && (
          <div className="space-y-4 animate-in slide-in-from-right">
             <input value={fullName} onChange={e => setFullName(e.target.value)} placeholder="Full Name" className="w-full p-4 rounded-xl bg-slate-50 border-none" />
             <input value={city} onChange={e => setCity(e.target.value)} placeholder="Current City" className="w-full p-4 rounded-xl bg-slate-50 border-none" />
             
             <div className="grid grid-cols-3 gap-2">
                {['Male', 'Female', 'Other'].map(g => (
                    <button key={g} onClick={() => setGender(g)} className={`py-3 rounded-xl font-medium border ${gender === g ? 'bg-slate-900 text-white' : 'border-slate-200'}`}>{g}</button>
                ))}
             </div>

             <div className="space-y-2 mt-4">
                <p className="text-xs font-bold text-slate-400 uppercase">Intent</p>
                {[{id: 'exploring', label: 'Exploring'}, {id: 'dating_marriage', label: 'Dating for Marriage'}, {id: 'ready_marriage', label: 'Ready for Marriage'}].map(i => (
                    <button key={i.id} onClick={() => setIntent(i.id)} className={`w-full p-3 rounded-xl border text-left ${intent === i.id ? 'border-slate-900 bg-slate-50' : 'border-slate-200'}`}>
                        {i.label}
                    </button>
                ))}
             </div>
          </div>
      )}

      {/* --- STEP 2: CAREER --- */}
      {step === 2 && (
          <div className="space-y-4 animate-in slide-in-from-right">
             <input value={jobTitle} onChange={e => setJobTitle(e.target.value)} placeholder="Job Title (e.g. Product Manager)" className="w-full p-4 rounded-xl bg-slate-50 border-none" />
             <input value={company} onChange={e => setCompany(e.target.value)} placeholder="Company Name" className="w-full p-4 rounded-xl bg-slate-50 border-none" />
             <input value={industry} onChange={e => setIndustry(e.target.value)} placeholder="Industry (e.g. Tech)" className="w-full p-4 rounded-xl bg-slate-50 border-none" />
             
             <div onClick={() => setCareerGhostMode(!careerGhostMode)} className="flex items-center gap-3 p-4 border rounded-xl cursor-pointer hover:bg-slate-50">
                 <div className={`w-5 h-5 rounded border flex items-center justify-center ${careerGhostMode ? 'bg-slate-900 border-slate-900' : 'border-slate-300'}`}>
                     {careerGhostMode && <div className="w-2 h-2 bg-white rounded-sm" />}
                 </div>
                 <div className="flex-1">
                     <p className="text-sm font-bold">Ghost Mode</p>
                     <p className="text-xs text-slate-500">Hide company name from public. Only visible to connections.</p>
                 </div>
             </div>
          </div>
      )}

      {/* --- STEP 3: FINANCIALS --- */}
      {step === 3 && (
          <div className="space-y-8 animate-in slide-in-from-right">
             <div className="text-center py-8">
                 <span className="text-6xl font-bold text-slate-900">₹{income}L</span>
                 <p className="text-slate-500 mt-2">Annual Income</p>
             </div>
             <input 
                type="range" min="5" max="100" step="1" 
                value={income} onChange={e => setIncome(parseInt(e.target.value))}
                className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-slate-900"
             />
             <div className="flex justify-between text-xs text-slate-400 font-bold">
                 <span>₹5L</span>
                 <span>₹1 Cr+</span>
             </div>
             <div className="bg-blue-50 p-4 rounded-xl flex gap-3 items-center">
                 <div className="p-2 bg-white rounded-full"><DollarSign size={16} className="text-blue-600"/></div>
                 <p className="text-xs text-blue-800">This is <b>Deep Data</b>. By default, it is blurred until you connect.</p>
             </div>
          </div>
      )}

      {/* --- STEP 4: LIFESTYLE --- */}
      {step === 4 && (
          <div className="space-y-6 animate-in slide-in-from-right">
             {[
                 { label: 'Diet', options: ['Veg', 'Non-Veg', 'Vegan'], val: diet, set: setDiet },
                 { label: 'Drink', options: ['Yes', 'No', 'Socially'], val: drink, set: setDrink },
                 { label: 'Smoke', options: ['Yes', 'No', 'Never'], val: smoke, set: setSmoke }
             ].map(cat => (
                 <div key={cat.label}>
                     <p className="text-sm font-bold text-slate-900 mb-2">{cat.label}</p>
                     <div className="flex flex-wrap gap-2">
                         {cat.options.map(opt => (
                             <button 
                                key={opt} 
                                onClick={() => cat.set(opt)}
                                className={`px-4 py-2 rounded-full text-sm border ${cat.val === opt ? 'bg-slate-900 text-white border-slate-900' : 'border-slate-200 text-slate-600'}`}
                             >
                                 {opt}
                             </button>
                         ))}
                     </div>
                 </div>
             ))}
          </div>
      )}

      {/* --- STEP 5: ROOTS --- */}
      {step === 5 && (
          <div className="space-y-6 animate-in slide-in-from-right">
             <div>
                <label className="block text-sm font-bold text-slate-900 mb-2">Religion</label>
                <select value={religion} onChange={e => setReligion(e.target.value)} className="w-full p-4 rounded-xl bg-slate-50 border-none">
                    <option value="">Select...</option>
                    <option value="Hindu">Hindu</option>
                    <option value="Muslim">Muslim</option>
                    <option value="Christian">Christian</option>
                    <option value="Sikh">Sikh</option>
                    <option value="Jain">Jain</option>
                    <option value="Other">Other</option>
                </select>
             </div>
             <div>
                <label className="block text-sm font-bold text-slate-900 mb-2">Family Type</label>
                <div className="flex gap-3">
                    {['Nuclear', 'Joint'].map(t => (
                        <button key={t} onClick={() => setFamilyType(t)} className={`flex-1 py-3 rounded-xl border ${familyType === t ? 'bg-slate-900 text-white' : 'border-slate-200'}`}>{t}</button>
                    ))}
                </div>
             </div>
          </div>
      )}

      {/* --- STEP 6: PREFERENCES --- */}
      {step === 6 && (
          <div className="space-y-6 animate-in slide-in-from-right">
             <div className="flex items-center gap-4">
                <div className="flex-1">
                    <label className="text-xs font-bold text-slate-500">Min Age</label>
                    <input type="number" value={prefMinAge} onChange={e => setPrefMinAge(e.target.value)} className="w-full p-4 rounded-xl bg-slate-50 border-none text-center font-bold" />
                </div>
                <span className="text-slate-300">-</span>
                <div className="flex-1">
                    <label className="text-xs font-bold text-slate-500">Max Age</label>
                    <input type="number" value={prefMaxAge} onChange={e => setPrefMaxAge(e.target.value)} className="w-full p-4 rounded-xl bg-slate-50 border-none text-center font-bold" />
                </div>
             </div>
             <div className="bg-slate-50 p-4 rounded-xl border border-slate-100 text-center">
                 <p className="text-sm text-slate-500">We'll show you people in <b>{city}</b> first.</p>
             </div>
          </div>
      )}

      {/* FOOTER ACTIONS */}
      <div className="mt-auto pt-8">
          <button 
            onClick={step === totalSteps ? handleComplete : handleNext}
            disabled={loading}
            className="w-full bg-slate-900 text-white font-bold py-4 rounded-xl shadow-lg flex items-center justify-center gap-2 active:scale-95 transition"
          >
            {loading ? <Loader2 className="animate-spin" /> : step === totalSteps ? "Complete Profile" : "Continue"} 
            {!loading && <ArrowRight size={20} />}
          </button>
      </div>

    </div>
  )
}